# base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/libreria_teruel_ayala?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=asd123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa / hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# puerto
server.port=8080
